apiVersion: v1
kind: ConfigMap
metadata:
  name: curvefs-scripts
  namespace: {{ .Release.Namespace }}
data:
  replace-config.sh: |+
{{ tuple "scripts/_replace_config.sh.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
