{{- if .Values.metaserver.enabled }}
{{- $g_role := "metaserver" }}
apiVersion: v1
kind: Service
metadata:
  name: metaserver-service
spec:
  type: ClusterIP
  clusterIP: None  # headless service
  ports:
    - name: metaserver-server
      port: {{ .Values.metaserver.port }}
      targetPort: {{ .Values.metaserver.port }}
      protocol: TCP
    - name: metaserver-client
      port: {{ .Values.metaserver.clientPort }}
      targetPort: {{ .Values.metaserver.clientPort }}
      protocol: TCP
  selector:
{{ tuple $g_role . | include "helm-toolkit.utils.selectorLabels" | indent 4 }}
{{- end }}
